version: '3'

services:
  client:
    container_name: client
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    volumes:
      - web-root:/usr/share/nginx/html
      - ../nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - web-root:/usr/share/nginx/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - client
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email yunusdemirpolatt@gmail.com --agree-tos --no-eff-email --force-renewal -d biligger.com  -d www.biligger.com 

  api:
    container_name: api
    image: yunusdp/biligger-api
    build:
      context: .
      args:
        NODE_ENV: production
    command: npm run start:prod
    restart: always
    depends_on:
      - mongo
      - redis
    env_file: .env
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - SESSION_SECRET=$SESSION_SECRET
      - REDIS_URL=redis://:$REDIS_PASSWORD@cache
      - SENDGRID_API_KEY=$SENDGRID_API_KEY

  mongo:
    container_name: db
    image: mongo
    restart: always
    command: ['--auth']
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
      
  redis:
    image: redis:alpine
    container_name: cache
    restart: always
    env_file: .env
    command: redis-server --appendonly yes --requirepass $REDIS_PASSWORD
    volumes:
      - redisdata:/data/redis

volumes:
  dbdata:
  redisdata:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/yunus/biligger/build/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/yunus/biligger/dhparam/
      o: bind
